{{- if .Values.serviceAccount.roleBinding.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.prow.podsNamespace }}
  name: {{ include "crier.roleName" . }}
  labels:
    {{- include "crier.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "events"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "patch"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.prow.podsNamespace }}
  name: {{ include "crier.roleBindingName" . }}
  labels:
    {{- include "crier.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "crier.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crier.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
