---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crier.fullname" . }}-github-token
  labels:
    {{- include "crier.labels" . | nindent 4 }}
stringData:
  cert: {{ .Values.prow.githubAppCert }}
  appid: {{ .Values.prow.githubAppId }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crier.fullname" . }}-hmac-token
  labels:
    {{- include "crier.labels" . | nindent 4 }}
stringData:
  # Generate via `openssl rand -hex 20`. This is the secret used in the GitHub webhook configuration
  hmac: {{ .Values.prow.githubHmacToken }}
