---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crier.fullname" . }}-github-token
  labels:
    {{- include "crier.labels" . | nindent 4 }}
stringData:
  cert: {{ .Values.prow.githubAppCert }}
  appid: {{ .Values.prow.githubAppId }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crier.fullname" . }}-hmac-token
  labels:
    {{- include "crier.labels" . | nindent 4 }}
stringData:
  # Generate via `openssl rand -hex 20`. This is the secret used in the GitHub webhook configuration
  hmac: {{ .Values.prow.githubHmacToken }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crier.fullname" . }}-s3-credentials
  labels:
    {{- include "crier.labels" . | nindent 4 }}
stringData:
  service-account.json: |
    {
      "region": "{{ .Values.prow.minioRegion }}",
      "access_key": "{{ .Values.prow.minioRootUser }}",
      "secret_key": "{{ .Values.prow.minioRootPassword }}",
      "endpoint": "minio.{{ .Release.Namespace }}.svc.cluster.local",
      "insecure": true,
      "s3_force_path_style": true
    }

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.prow.podsNamespace }}
  name: {{ include "crier.fullname" . }}-s3-credentials
  labels:
    {{- include "crier.labels" . | nindent 4 }}
stringData:
  service-account.json: |
    {
      "region": "{{ .Values.prow.minioRegion }}",
      "access_key": "{{ .Values.prow.minioRootUser }}",
      "secret_key": "{{ .Values.prow.minioRootPassword }}",
      "endpoint": "minio.{{ .Release.Namespace }}.svc.cluster.local",
      "insecure": true,
      "s3_force_path_style": true
    }
