{{- if .Values.serviceAccount.roleBinding.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hook.roleName" . }}
  labels:
    {{- include "hook.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hook.roleBindingName" . }}
  labels:
    {{- include "hook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hook.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hook.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
