{{- if .Values.serviceAccount.roleBinding.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.prow.podsNamespace }}
  name: {{ include "crier.role" . }}
  labels:
    {{- include "crier.labels" . | nindent 4 }}
- apiGroups:
    - ""
  resources:
    - "pods"
    - "events"
  verbs:
    - "get"
    - "list"
- apiGroups:
    - ""
  resources:
    - "pods"
  verbs:
    - "patch"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.prow.podsNamespace }}
  name: {{ include "crier.roleBinding" . }}
  labels:
    {{- include "crier.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crier
subjects:
  - kind: ServiceAccount
    name: {{ include "crier.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}  
{{- end }}