apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghproxy.fullname" . }}
  labels:
    {{- include "ghproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
  selector:
    {{- include "ghproxy.selectorLabels" . | nindent 4 }}
