{{- if .Values.serviceAccount.roleBinding.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prow-controller-manager.roleName" . }}
  labels:
    {{- include "prow-controller-manager.labels" . | nindent 4 }}  
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - prow-controller-manager-leader-lock
    verbs:
      - get
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - prow-controller-manager-leader-lock
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - create

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prow-controller-manager.roleBindingName" . }}
  labels:
    {{- include "prow-controller-manager.labels" . | nindent 4 }}  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prow-controller-manager.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prow-controller-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
