name: test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    
jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        uses: ./.github/actions/flux2/tools
      - name: Validate manifests
        run: |
          chmod +x ./flux2/multi-clusters/scripts/validate.sh
          ./flux2/multi-clusters/scripts/validate.sh