# verify with local kind k8s cluster.
name: Flux2 E2E test

on:
  push:
    branches: [main]
    paths: 
      - "flux2/**"

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        cluster: [staging, prod]
        solution: [multi-clusters, multi-tenants]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup tools
        uses: ./.github/actions/flux2/tools
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: Bootstrap Flux in Kubernetes kind
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          flux check --pre
          flux bootstrap github \
            --owner=${GITHUB_REPOSITORY_OWNER} \
            --repository=$(basename ${GITHUB_REPOSITORY}) \
            --branch=${GITHUB_REF_NAME} \
            --path=./flux2/${{ matrix.solution }}/clusters/${{ matrix.cluster }}

      - name: Verify reconciliations
        timeout-minutes: 5
        run: |
          while flux get all --all-namespaces --status-selector=ready=false | grep False
          do
            sleep 5
          done
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces