{{- if .Values.serviceAccount.roleBinding.create }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "deck.roleName" . }}
  labels:
    {{- include "deck.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - get
      - list
      - watch
      # Required when deck runs with `--rerun-creates-job=true`
      # **Warning:** Only use this for non-public deck instances, this allows
      # anyone with access to your Deck instance to create new Prowjobs
      # - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "deck.roleBindingName" . }}
  labels:
    {{- include "deck.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "deck.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "deck.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
