{{- if .Values.serviceAccount.roleBinding.create }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "deck.roleName" . }}
  labels:
    {{- include "deck.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - get
      - list
      - watch
      # Required when deck runs with `--rerun-creates-job=true`
      # **Warning:** Only use this for non-public deck instances, this allows
      # anyone with access to your Deck instance to create new Prowjobs
      # - create
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.prow.podsNamespace }}
  name: {{ include "deck.roleName" . }}
  labels:
    {{- include "deck.labels" . | nindent 4 }}  
rules:
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
{{- end }}
